name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📤 Upload via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Upload to cPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        
        with:
          username: ${{ secrets.CPANEL_USER }}
          server: ${{ secrets.CPANEL_HOST }}
          port: 21
          password: ${{ secrets.CPANEL_PASSWORD }}
          local_path: ./
          remote_path: /home/eric/public_html/htdocs/whisprrz.com/
          sftp_only: true