name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📤 Upload via SFTP
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 📤 Upload to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        username: ${{ secrets.CPANEL_USER }}
        server: ${{ secrets.CPANEL_HOST }}
        port: 21
        password: ${{ secrets.CPANEL_PASSWORD }}
        protocol: ftp
        local-dir: ./
        server-dir: public_html/htdocs/whisprrz.com/
        exclude: |
          **/node_modules/**
          **/.git/**
          **/_cron/**
          **/files/**        # Often used for user uploads, you don’t want to wipe this
          **/incube/**       # Might be licensing or runtime-related
          **/m/**            # Could be minified or media-related content
          **/pay/**          # Likely related to payment logic or logs
          **/partner/**      # External/internal integration, avoid overwriting
          **/wow/**          # May contain non-versioned or sensitive logic
          **/.well-known/**  # For SSL, domain verification — hands off
          **/lang/**         # If languages are managed server-side
        timeout: 180