name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📤 Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Upload to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          username: ${{ secrets.CPANEL_USER }}
          server: ${{ secrets.CPANEL_HOST }}
          port: 21
          password: ${{ secrets.CPANEL_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: /public_html/htdocs/whisprrz.com/
          dangerous-clean-slate: false
          timeout: 60
    env:
      FTP_VERBOSE: true